version: 2

project_name: fiso

builds:
  - id: fiso-flow
    binary: fiso-flow
    main: ./cmd/fiso-flow
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: fiso-link
    binary: fiso-link
    main: ./cmd/fiso-link
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: fiso-operator
    binary: fiso-operator
    main: ./cmd/fiso-operator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: fiso
    binary: fiso
    main: ./cmd/fiso
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

dockers_v2:
  - id: fiso-flow
    ids: [fiso-flow]
    images:
      - "ghcr.io/lsm/fiso-flow"
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile.goreleaser
    build_args:
      BINARY: fiso-flow

  - id: fiso-link
    ids: [fiso-link]
    images:
      - "ghcr.io/lsm/fiso-link"
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile.goreleaser
    build_args:
      BINARY: fiso-link

  - id: fiso-operator
    ids: [fiso-operator]
    images:
      - "ghcr.io/lsm/fiso-operator"
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile.goreleaser
    build_args:
      BINARY: fiso-operator

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
