FROM alpine:3.20
ARG BINARY=fiso-flow
ARG TARGETPLATFORM
RUN apk add --no-cache ca-certificates tzdata
COPY ${TARGETPLATFORM}/${BINARY} /usr/local/bin/${BINARY}
RUN adduser -D -u 1000 fiso && ln -s /usr/local/bin/${BINARY} /usr/local/bin/entrypoint
USER fiso
ENTRYPOINT ["entrypoint"]
